name = "StataCall"
uuid = "149ba50c-99c4-11e9-1e32-e960083e84dc"
authors = ["Johannes Boehm <johannes.boehm@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
StatFiles = "1463e38c-9381-5320-bcd4-4134955f093a"

[compat]
CSV = ">= 0.5.6"
DataFrames = ">= 0.18.3"
FileIO = ">= 1.0.7"
StatFiles = ">= 0.8.0"
julia = "1"


[extras]
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Missings"]
